#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10
GITHUB_OWNER="SeriousJul"
REPO="my-little-software-factory"
WORKFLOW_FILE="release.yml"
PACKAGES=("my-little-software-factory" "mlsf")
STAGE_TAG="v0.0.2"
FIRST_RELEASE="v0.1.0"

# The wizard stores its memory outside the repository: no npm value lands in a
# file a git command could push.
ENV_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/my-little-software-factory/npm-trusted-publishing.env"
mkdir -p "$(dirname "$ENV_FILE")"

banner "npm trusted publishing setup for $REPO"

# ── Stage 1: check prerequisites ─────────────────────────────────────────
stage "Check prerequisites"
if command -v npm >/dev/null 2>&1; then
  npm_version="$(npm --version 2>/dev/null || echo 0.0.0)"
  npm_ok="$(awk -v v="$npm_version" 'BEGIN { split(v, a, "."); print (a[1] > 11 || (a[1] == 11 && a[2] >= 5)) ? 1 : 0 }')"
  if [[ "$npm_ok" == "1" ]]; then
    say "npm $npm_version is at 11.5.1 or above"
  else
    warn "npm $npm_version is below 11.5.1; trusted publishing needs a newer npm. Update it and re-run."
    exit 1
  fi
else
  warn "npm is not on this machine; install Node 22.14 or above with npm, then re-run."
  exit 1
fi
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "gh is signed in"
else
  warn "gh is not signed in; the stale release stage will skip. Run: gh auth login"
fi
origin_url="$(git remote get-url origin 2>/dev/null || true)"
case "$origin_url" in
  *"$GITHUB_OWNER/$REPO"*) say "this is the $GITHUB_OWNER/$REPO checkout" ;;
  *) warn "this checkout's origin is '$origin_url', not $GITHUB_OWNER/$REPO. The tag stages assume the right repository." ;;
esac
pause

# ── Stage 2: remove the stale release and tag ────────────────────────────
stage "Remove the stale $STAGE_TAG release"
say "The $STAGE_TAG tag ran the old workflow and left an empty pre-release."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  release_gone=1
  tag_gone=1
  if ! gh release view "$STAGE_TAG" >/dev/null 2>&1; then
    say "no $STAGE_TAG release on GitHub"
  else
    release_gone=0
  fi
  if [[ -z "$(git ls-remote --tags origin "refs/tags/$STAGE_TAG" 2>/dev/null || true)" ]]; then
    say "no $STAGE_TAG tag on the remote"
  else
    tag_gone=0
  fi
  if (( release_gone && tag_gone )); then
    say "nothing to remove"
  elif confirm "Delete the $STAGE_TAG release and the $STAGE_TAG tag?"; then
    (( release_gone )) || gh release delete "$STAGE_TAG" --yes
    if (( ! tag_gone )); then
      git push origin ":refs/tags/$STAGE_TAG"
      git tag -d "$STAGE_TAG" >/dev/null 2>&1 || true
    fi
    say "the stale release and tag are gone"
  else
    say "kept; the stale release will sit as an empty pre-release"
  fi
else
  warn "gh is not signed in, so the wizard cannot check or delete the $STAGE_TAG release"
fi
pause

# ── Stage 3: create the one-off token ────────────────────────────────────
stage "Create the one-off token"
say "An npm account with two-factor authentication cannot publish through the"
say "CLI's browser login. The one-off granular token below carries the"
say "two-factor bypass for this run alone. Stage 9 revokes it, and the"
say "workflow never sees it: the release authenticates with the OIDC token"
say "GitHub hands the runner."
TOKEN_NPMRC="$(mktemp)"
chmod 600 "$TOKEN_NPMRC"
note "the token sits in a scratch file the wizard deletes in stage 9; it never touches your npm config"
ask NPM_USER "Your npm user name, the one on your npmjs.com profile:"
if [[ -n "${NPM_USER:-}" ]]; then
  write_env NPM_USER "$NPM_USER"
  open_url "https://www.npmjs.com/settings/$NPM_USER/tokens"
else
  warn "no user name, so open the page by hand: profile picture, upper right, then Access Tokens"
  open_url "https://www.npmjs.com"
fi
step "Sign in to npmjs.com in the browser, if the page asks."
step "Click Generate New Token."
step "Token name: claim-package-names."
step "Check Bypass two-factor authentication."
step "Permissions: Read and write (publish and stage). Select Packages: All Packages."
step "Expiration: the shortest option; the page needs at least one day."
step "Click Generate Token and copy the token from the top of the page."
ask_secret NPM_TOKEN "Paste the token:"
if [[ -n "${NPM_TOKEN:-}" ]]; then
  printf '//registry.npmjs.org/:_authToken=%s\n' "$NPM_TOKEN" > "$TOKEN_NPMRC"
  say "token in hand"
else
  warn "no token, so the claim stages will skip; re-run the wizard to do them"
fi
pause

# ── Stage 4 and 5: claim both package names ─────────────────────────────
for pkg in "${PACKAGES[@]}"; do
  stage "Claim the name $pkg"
  if npm view "$pkg" version >/dev/null 2>&1; then
    say "$pkg already exists on the registry (version $(npm view "$pkg" version 2>/dev/null)); no claim needed"
    pause
    continue
  fi
  say "npm cannot configure trusted publishing for a name that does not exist."
  say "The wizard publishes a 0.0.0 placeholder to claim the name, and stage 6"
  say "marks the placeholder deprecated. The first real version publishes from"
  say "the workflow with provenance."
  if [[ -z "${NPM_TOKEN:-}" ]]; then
    SKIPPED+=("claim the name $pkg (run the wizard with the one-off token)")
    warn "no token, so the wizard cannot claim $pkg"
  elif confirm "Claim the public name $pkg with a 0.0.0 placeholder?"; then
    stub_dir="$(mktemp -d)"
    cat > "$stub_dir/package.json" <<EOF
{
  "name": "$pkg",
  "version": "0.0.0",
  "description": "Placeholder published to configure trusted publishing; install a real version."
}
EOF
    ( cd "$stub_dir" && npm publish --access public --registry https://registry.npmjs.org --userconfig "$TOKEN_NPMRC" )
    rm -rf "$stub_dir"
    say "claimed $pkg at 0.0.0"
  else
    SKIPPED+=("claim the name $pkg (publish its 0.0.0 placeholder)")
    warn "skipped; nobody can publish $pkg until the name is claimed"
  fi
  pause
done

# ── Stage 6: deprecate the placeholders ──────────────────────────────────
stage "Deprecate the 0.0.0 placeholders"
for pkg in "${PACKAGES[@]}"; do
  if npm view "$pkg" version >/dev/null 2>&1; then
    if npm deprecate "$pkg@0.0.0" \
      "placeholder published to configure trusted publishing; install 0.1.0 or later" \
      --registry https://registry.npmjs.org --userconfig "$TOKEN_NPMRC" 2>/dev/null; then
      say "deprecate notice set on $pkg@0.0.0"
    else
      note "$pkg@0.0.0 could not be deprecated here; set the notice from npmjs.com"
    fi
  else
    note "$pkg does not exist on the registry; nothing to deprecate"
  fi
done
pause

# ── Stage 7 and 8: configure the trusted publisher on each package ──────
for pkg in "${PACKAGES[@]}"; do
  stage "Grant trusted publishing to $pkg"
  open_url "https://www.npmjs.com/package/$pkg"
  step "On the package page, open the Settings tab."
  step "In the Trusted publishing section, click Add trusted publisher."
  step "Select the GitHub Actions provider."
  step "Organization or user: $GITHUB_OWNER"
  step "Repository: $REPO"
  step "Workflow filename: $WORKFLOW_FILE  (the bare name, the .yml included)"
  step "Environment name: leave empty."
  step "Allowed actions: select npm publish so the workflow may publish directly."
  warn "npm does not check these values when you save them."
  warn "A wrong value fails the first real publish, with the error naming the mismatch."
  pause "Press Enter when you saved the trusted publisher"
done

# ── Stage 9: revoke the token ────────────────────────────────────────────
stage "Revoke the token"
if [[ -n "${NPM_USER:-}" ]]; then
  open_url "https://www.npmjs.com/settings/$NPM_USER/tokens"
else
  warn "open the page by hand: profile picture, upper right, then Access Tokens"
  open_url "https://www.npmjs.com"
fi
step "On the tokens page, find claim-package-names and revoke it."
rm -f "$TOKEN_NPMRC"
say "the scratch file is deleted; your npm config never held the token"
say "From this point the only publish path is the workflow's OIDC token."
pause

# ── Stage 10: cut the first release ──────────────────────────────────────
stage "Cut the first release $FIRST_RELEASE"
say "This tag is the real test: npm checks the grant when the publish step"
say "runs, not when you saved it. The tag is the only release action; the"
say "workflow writes the tag's version into both manifests (ADR 0090)."
open_url "https://github.com/$GITHUB_OWNER/$REPO/releases/new"
step "In the Choose a tag box, type $FIRST_RELEASE and press Enter."
step "Set the release title to $FIRST_RELEASE and click Create release."
open_url "https://github.com/$GITHUB_OWNER/$REPO/actions"
step "Watch the Release run. Checks, the npm publish, and the seven build"
step "legs all have to pass before the release carries its binaries."
say "If the publish step fails with ENEEDAUTH, the grant's repository or"
say "workflow filename does not match $GITHUB_OWNER/$REPO and $WORKFLOW_FILE."
say "Fix the grant on the package's Settings page and re-run the job."
pause "Press Enter when the run has started"

# ──────────────────────────────────────────────────────────────────────────
finish
